### ISSUE TITLE
Make a prefix for the debbuger

### ISSUE THREAD

**Issue by joseims** [joseims/InsideOutDebugger#3]
**What:**
Create a prefix so the user know when the debugger in running, and not the code.

**Why:**
To make it easier to use the InsideOutDebugger

**How:**
Create a prefix to the user when he is pro,pted to write the command, similar to what the bash does. The prefix must be able to be passed as a named argument to the main function, but there should be a default one. It must be good looking and simple.

**Comment by Blastoise** [comment]
I'm picking this up!

**Comment by joseims** [comment]
Done
